version: "3"

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2
      - ./data/config:/etc/influxdb2
    expose:
      - 8086
    environment:
      - INFLUX_HOST=${INFLUX_URL}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - VIRTUAL_HOST=${VHOST}
      - VIRTUAL_PORT=8086
      - LETSENCRYPT_HOST=${LHOST}
      - LETSENCRYPT_EMAIL=${LEMAIL}
networks:
  default:
    external: true
    name: nginx-proxy
